import os
import json
import asyncio
from google.adk.workflow import node
from agent.state import AgentState
from agent.llm_client import generate_text
from agent.mock_utils import MOCK_MODE

# Mock results for Issue #15 (idempotency key support) in the demo PR
MOCK_SPEC_RESULTS = [
    {
        "criterion": "Every payment request must accept an idempotency_key string parameter",
        "status": "SATISFIED",
        "confidence": "HIGH",
        "evidence": "models.py: L22 idempotency_key: str = field(default_factory=lambda: str(uuid.uuid4()))",
        "reasoning": "The PaymentRequest dataclass includes the idempotency_key string field.",
        "line_ref": "src/models.py:22"
    },
    {
        "criterion": "Duplicate requests with same key must return cached response",
        "status": "SATISFIED",
        "confidence": "HIGH",
        "evidence": "payment_processor.py: L50 if request.idempotency_key in self._processed_cache:",
        "reasoning": "The processor checks the cache and returns the cached result if the key matches.",
        "line_ref": "src/payment_processor.py:50"
    },
    {
        "criterion": "idempotency_key must be validated — non-empty string, maximum 64 characters",
        "status": "MISSING",
        "confidence": "HIGH",
        "evidence": "None",
        "reasoning": "No validation check for string length or emptiness of the idempotency_key was found in the diff.",
        "line_ref": None
    },
    {
        "criterion": "Cache TTL must be configurable via Config (not hardcoded)",
        "status": "PARTIAL",
        "confidence": "HIGH",
        "evidence": "payment_processor.py: L46 self._idempotency_ttl = 86400",
        "reasoning": "The cache TTL is hardcoded to 86400 in PaymentProcessor instead of using Config.IDEMPOTENCY_CACHE_TTL_SECONDS.",
        "line_ref": "src/payment_processor.py:46"
    },
    {
        "criterion": "If no key provided, generate UUID automatically",
        "status": "SATISFIED",
        "confidence": "HIGH",
        "evidence": "models.py: L22 idempotency_key: str = field(default_factory=lambda: str(uuid.uuid4()))",
        "reasoning": "A UUID is generated by default if the key is omitted.",
        "line_ref": "src/models.py:22"
    },
    {
        "criterion": "Unit tests must cover: duplicate key returns same result, key over 64 chars rejected, expired key allows re-processing",
        "status": "PARTIAL",
        "confidence": "HIGH",
        "evidence": "test_payment_processor.py: L40 test_idempotency_duplicate_returns_cached_result",
        "reasoning": "Duplicate test is present, but no test covers the expired key re-processing scenario.",
        "line_ref": "tests/test_payment_processor.py:40"
    }
]

@node
async def spec_compliance_node(state: AgentState) -> AgentState:
    """SpecComplianceNode to verify each criterion against the PR diff."""
    if not state.acceptance_criteria:
        print("No acceptance criteria to verify.")
        state.spec_results = []
        return state

    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GROQ_API_KEY") or os.getenv("OPENROUTER_API_KEY")
    if MOCK_MODE or not api_key or api_key.startswith("your_") or api_key == "dummy":
        print("[MOCK LLM] Returning mock spec compliance results.")
        # Filter mock results to match the loaded acceptance criteria
        matched_results = []
        for criterion in state.acceptance_criteria:
            found = False
            for mock in MOCK_SPEC_RESULTS:
                if mock["criterion"].lower() in criterion.lower() or criterion.lower() in mock["criterion"].lower():
                    matched_results.append({
                        "criterion": criterion,
                        "status": mock["status"],
                        "confidence": mock["confidence"],
                        "evidence": mock["evidence"],
                        "reasoning": mock["reasoning"],
                        "line_ref": mock["line_ref"]
                    })
                    found = True
                    break
            if not found:
                matched_results.append({
                    "criterion": criterion,
                    "status": "MISSING",
                    "confidence": "LOW",
                    "evidence": "None",
                    "reasoning": "Mock fallback: criterion not matched in mock database.",
                    "line_ref": None
                })
        state.spec_results = matched_results
        
        # Apply merge blocker rule: MISSING or PARTIAL with HIGH confidence
        for result in state.spec_results:
            if result["status"] in ("MISSING", "PARTIAL") and result["confidence"] == "HIGH":
                state.merge_blockers.append(result)
        return state

    # Real LLM Spec Compliance Check
    print("Running spec compliance analysis with fallback LLMs...")
    spec_results = []
    
    for idx, criterion in enumerate(state.acceptance_criteria):
        if idx > 0:
            print("Sleeping 2 seconds to avoid LLM rate limit...")
            await asyncio.sleep(2.0)
            
        prompt = f"""You are verifying whether a code change satisfies a specific acceptance criterion.

Acceptance criterion: {criterion}

PR diff:
{state.pr_diff}

Analyze the diff carefully. Return JSON:
{{
  "criterion": "{criterion}",
  "status": "SATISFIED" | "PARTIAL" | "MISSING",
  "confidence": "HIGH" | "MEDIUM" | "LOW",
  "evidence": "exact quote or line reference from the diff that supports your conclusion",
  "reasoning": "one sentence explanation",
  "line_ref": "filename:line_number if applicable, else null"
}}

Rules:
- SATISFIED: the diff clearly implements what the criterion asks
- PARTIAL: the diff partially addresses it but something is missing
- MISSING: the diff does not address this criterion at all
- If you cannot determine with confidence, set confidence to LOW
- Never guess. Never hallucinate line numbers. Only reference what is in the diff.
"""
        try:
            response_text = await generate_text(prompt, role="final", response_mime_type="application/json")
            result = json.loads(response_text)
            spec_results.append(result)
            
            # Apply merge blocker rule
            if result.get("status") in ("MISSING", "PARTIAL") and result.get("confidence") == "HIGH":
                state.merge_blockers.append(result)
        except Exception as e:
            print(f"Error evaluating criterion '{criterion}': {e}")
            spec_results.append({
                "criterion": criterion,
                "status": "MISSING",
                "confidence": "LOW",
                "evidence": "Error during evaluation",
                "reasoning": str(e),
                "line_ref": None
            })

    state.spec_results = spec_results
    return state
